-- Data-only migration, written by hand — NOT generated by `prisma migrate
-- dev`. Do not run `prisma migrate dev` to regenerate or extend this: it
-- diffs the real database against schema.prisma, sees the two GIN indexes on
-- CanonicalProduct.searchVector/name that schema.prisma cannot declare (an
-- Unsupported("tsvector") column), and proposes DROPping them
-- (.agent/playbook/prisma-migrate-dev-borra-indices-gin-no-declarados.md).
--
-- prisma/schema.prisma is untouched by F-015: not a column, not an index.
-- This migration exists only so that no environment is left with a mute
-- search index by omission (ADR 0010 left `postinstall` without
-- `migrate deploy`, so production depends on this file, not on someone
-- remembering to run a script). Applied by `npx prisma migrate deploy`,
-- which is what the CI runs before `npm test`, against an empty database —
-- there it updates 0 rows and does nothing else.
--
-- 'spanish' is a literal, not an import: a .sql file cannot import
-- MARKETPLACE_SEARCH_TS_CONFIG (src/constants/marketplace.ts). The guard at
-- src/features/marketplace/server/boundaries.test.ts (G3) compares this
-- literal against the constant so the two cannot drift apart silently.
--
-- No LIMIT and no loop: a migration runs exactly once, over whatever the
-- table holds at that moment — unlike the batched executable
-- (scripts/backfill-search-vector.ts) a developer runs locally instead
-- (PP2: this migration is not applied against the shared local database).
--
-- Idempotent (R13): a row with a non-NULL searchVector never matches the
-- WHERE below again, so running this twice, or running it after the
-- executable already did the same work, updates 0 rows (E20).
UPDATE "CanonicalProduct"
   SET "searchVector" = to_tsvector('spanish', unaccent("searchDocument"))
 WHERE "id" IN (
         SELECT "id"
           FROM "CanonicalProduct"
          WHERE "searchVector" IS NULL
       );
