import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`, rewritten on every install.
    "src/generated/**",
    "coverage/**",
  ]),

  {
    rules: {
      // Same convention as cuadrecaja: unused vars are an error, `_` opts out.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
    },
  },

  {
    /**
     * Layering rule, enforced rather than merely documented: pages and
     * components go through features/*_/server, they do not reach for Prisma.
     */
    files: ["src/components/**/*.{ts,tsx}", "src/app/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/prisma", "@/generated/prisma/client", "@prisma/client"],
              message:
                "Components and pages must not touch Prisma. Go through features/*/server instead.",
            },
          ],
        },
      ],
    },
  },
]);
