import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`, rewritten on every install.
    "src/generated/**",
    "coverage/**",
  ]),

  {
    rules: {
      // Same convention as cuadrecaja: unused vars are an error, `_` opts out.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
    },
  },

  {
    /**
     * Layering rule, enforced rather than merely documented: pages and
     * components go through features/*_/server, they do not reach for Prisma.
     */
    files: ["src/components/**/*.{ts,tsx}", "src/app/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/prisma", "@/generated/prisma/client", "@prisma/client"],
              message:
                "Components and pages must not touch Prisma. Go through features/*/server instead.",
            },
            {
              // F-041 (architecture.md § Escalabilidad, punto 6): the zone
              // index is ~7 KB gzip that `check:bundle` would NOT catch if it
              // leaked into a client chunk — there is no client reader of it
              // until F-042. This rule is one of the two guarantees (the
              // other is `src/features/zones/boundaries.test.ts`, por crear,
              // whose allow-list also covers the checkout components this
              // pattern cannot reach).
              group: ["@/features/zones/catalog", "@/features/zones/zone-index.json"],
              message:
                "The zone catalog index is server-only until F-042. Client components must not import it.",
            },
          ],
        },
      ],
    },
  },

  {
    // F-023 (R1, architecture.md § Cinco cosas… punto 5): `next/image` is
    // gone for good (`images.unoptimized: true`), so the ONE place in the
    // repo that emits a raw `<img>` is deliberate, not a regression the
    // default `no-img-element` warning exists to catch. Scoped to this one
    // file, not the whole `components/ui/` directory.
    files: ["src/components/ui/ResponsiveImage.tsx"],
    rules: {
      "@next/next/no-img-element": "off",
    },
  },
]);
